function returnAll() {
  const themes = [
    { id: "animals", name: "Animal Welfare" },
    { id: "agriculture", name: "Sustainable Agriculture" },
    { id: "art", name: "Arts and Culture" },
    { id: "children", name: "Child Protection" },
    { id: "climate", name: "Climate Action" },
    { id: "covid-19", name: "COVID-19" },
    { id: "democ", name: "Peace and Reconciliation" },
    { id: "disability", name: "Disability Rights" },
    { id: "disaster", name: "Disaster Response" },
    { id: "ecdev", name: "Economic Growth" },
    { id: "edu", name: "Education" },
    { id: "endabuse", name: "Ending Abuse" },
    { id: "env", name: "Ecosystem Restoration" },
    { id: "gender", name: "Gender Equality" },
    { id: "health", name: "Physical Health" },
    { id: "housing", name: "Safe Housing" },
    { id: "human", name: "Ending Human Trafficking" },
    { id: "hunger", name: "Food Security" },
    { id: "lgbtq", name: "LGBTQIA+ Equality" },
    { id: "justice", name: "Racial Justice" },
    { id: "mentalhealth", name: "Mental Health" },
    { id: "refugee", name: "Refugee Rights" },
    { id: "rights", name: "Justice and Human Rights" },
    { id: "reproductive", name: "Reproductive Health" },
    { id: "sport", name: "Sport" },
    { id: "tech", name: "Digital Literacy" },
    { id: "water", name: "Clean Water" },
    { id: "wildlife", name: "Wildlife Conservation" },
    { id: "none", name: " noTheme" },
  ];
  return themes;
}
exports.returnAll = returnAll;
